import uniqid from 'uniqid'
const mongoose = require("mongoose");



var SchemaTypes = mongoose.Schema.Types;

const Data = mongoose.model(
  "Data",
  new mongoose.Schema({
    mod_id:{
      type: String,
      required:true
    },
    name: {
      type: String,
      required:true
    },
    Age:{
      type: Number,
      required:true
    },
    Sex: {
      type: String,
      required:true
    },
    itching:{
      type:Number,
      default:0
  },
  skin_rash:{
      type:Number,
      default:0
  },	
  nodal_skin_eruptions:{
      type:Number,
      default:0
  },	
  continuous_sneezing:{
      type:Number,
      default:0
  },	
  shivering:{
      type:Number,
      default:0
  },	
  chills:{
      type:Number,
      default:0
  },	
  joint_pain:{
      type:Number,
      default:0
  },	
  stomach_pain:{
      type:Number,
      default:0
  },	
  acidity:{
      type:Number,
      default:0
  },	
  ulcers_on_tongue:{
      type:Number,
      default:0
  },	
  muscle_wasting:{
      type:Number,
      default:0
  },	
  vomiting:{
      type:Number,
      default:0
  },	
  burning_micturition:{
      type:Number,
      default:0
  },	
  spotting_urination:{
      type:Number,
      default:0
  },	
  fatigue:{
      type:Number,
      default:0
  },	
  weight_gain:{
      type:Number,
      default:0
  },	
  anxiety:{
      type:Number,
      default:0
  },	
  cold_hands_and_feets:{
      type:Number,
      default:0
  },	
  mood_swings:{
      type:Number,
      default:0
  },	
  weight_loss:{
      type:Number,
      default:0
  },	
  restlessness:{
      type:Number,
      default:0
  },	
  lethargy:{
      type:Number,
      default:0
  },	
  patches_in_throat:{
      type:Number,
      default:0
  },	
  irregular_sugar_level:{
      type:Number,
      default:0
  },	
  cough:{
      type:Number,
      default:0
  },	
  high_fever:{
      type:Number,
      default:0
  },	
  sunken_eyes:{
      type:Number,
      default:0
  },	
  breathlessness:{
      type:Number,
      default:0
  },	
  sweating:{
      type:Number,
      default:0
  },	
  dehydration:{
      type:Number,
      default:0
  },	
  indigestion:{
      type:Number,
      default:0
  },	
  headache:{
      type:Number,
      default:0
  },	
  yellowish_skin:{
      type:Number,
      default:0
  },	
  dark_urine:{
      type:Number,
      default:0
  },	
  nausea:{
      type:Number,
      default:0
  },	
  loss_of_appetite:{
      type:Number,
      default:0
  },	
  pain_behind_the_eyes:{
      type:Number,
      default:0
  },	
  back_pain:{
      type:Number,
      default:0
  },	
  constipation:{
      type:Number,
      default:0
  },	
  abdominal_pain:{
      type:Number,
      default:0
  },	
  diarrhoea:{
      type:Number,
      default:0
  },	
  mild_fever:{
      type:Number,
      default:0
  },	
  yellow_urine:{
      type:Number,
      default:0
  },	
  yellowing_of_eyes:{
      type:Number,
      default:0
  },	
  acute_liver_failure:{
      type:Number,
      default:0
  },	
  fluid_overload:{
      type:Number,
      default:0
  },	
  swelling_of_stomach:{
      type:Number,
      default:0
  },	
  swelled_lymph_nodes:{
      type:Number,
      default:0
  },	
  malaise:{
      type:Number,
      default:0
  },	
  blurred_and_distorted_vision:{
      type:Number,
      default:0
  },	
  phlegm:{
      type:Number,
      default:0
  },	
  throat_irritation:{
      type:Number,
      default:0
  },	
  redness_of_eyes:{
      type:Number,
      default:0
  },	
  sinus_pressure:{
      type:Number,
      default:0
  },	
  runny_nose:{
      type:Number,
      default:0
  },	
  congestion:{
      type:Number,
      default:0
  },	
  chest_pain:{
      type:Number,
      default:0
  },	
  weakness_in_limbs:{
      type:Number,
      default:0
  },	
  fast_heart_rate:{
      type:Number,
      default:0
  },	
  pain_during_bowel_movements:{
      type:Number,
      default:0
  },	
  pain_in_anal_region:{
      type:Number,
      default:0
  },	
  bloody_stool:{
      type:Number,
      default:0
  },	
  irritation_in_anus:{
      type:Number,
      default:0
  },	
  neck_pain:{
      type:Number,
      default:0
  },
  dizziness:{
      type:Number,
      default:0
  },	
  cramps:{
      type:Number,
      default:0
  },	
  
  bruising:{
      type:Number,
      default:0
  },	
  obesity:{
      type:Number,
      default:0
  },	
  swollen_legs:{
      type:Number,
      default:0
  },	
  swollen_blood_vessels:{
      type:Number,
      default:0
  },	
  puffy_face_and_eyes:{
      type:Number,
      default:0
  },	
  enlarged_thyroid:{
      type:Number,
      default:0
  },
  brittle_nails:{
      type:Number,
      default:0
  },	
  swollen_extremeties:{
      type:Number,
      default:0
  },	
  excessive_hunger:{
      type:Number,
      default:0
  },	
  extra_marital_contacts:{
      type:Number,
      default:0
  },	
  drying_and_tingling_lips:{
      type:Number,
      default:0
  },	
  slurred_speech:{
      type:Number,
      default:0
  },	
  knee_pain:{
      type:Number,
      default:0
  },	
  hip_joint_pain:{
      type:Number,
      default:0
  },	
  muscle_weakness:{
      type:Number,
      default:0
  },	
  stiff_neck:{
      type:Number,
      default:0
  },	
  swelling_joints:{
      type:Number,
      default:0
  },	
  movement_stiffness:{
      type:Number,
      default:0
  },	
  spinning_movements:{
      type:Number,
      default:0
  },	
  loss_of_balance:{
      type:Number,
      default:0
  },	
  unsteadiness:{
      type:Number,
      default:0
  },	
  weakness_of_one_body_side:{
      type:Number,
      default:0
  },
  loss_of_smell:{
      type:Number,
      default:0
  },	
  bladder_discomfort:{
      type:Number,
      default:0
  },	
  foul_smell_of_urine:{
      type:Number,
      default:0
  },	
  continuous_feel_of_urine:{
      type:Number,
      default:0
  },	
  passage_of_gases:{
      type:Number,
      default:0
  },	
  internal_itching:{
      type:Number,
      default:0
  },	
  toxic_look_typhos:{
      type:Number,
      default:0
  },	
  depression:{
      type:Number,
      default:0
  },	
  irritability:{
      type:Number,
      default:0
  },	
  muscle_pain:{
      type:Number,
      default:0
  },	
  altered_sensorium:{
      type:Number,
      default:0
  },	
  red_spots_over_body:{
      type:Number,
      default:0
  },
  belly_pain:{
      type:Number,
      default:0
  },	
  abnormal_menstruation:{
      type:Number,
      default:0
  },	
  dischromic_patches:{
      type:Number,
      default:0
  },
  watering_from_eyes:{
      type:Number,
      default:0
  },	
  increased_appetite:{
      type:Number,
      default:0
  },	
  polyuria:{
      type:Number,
      default:0
  },	
  family_history:{
      type:Number,
      default:0
  },	
  mucoid_sputum:{
      type:Number,
      default:0
  },	
  rusty_sputum:{
      type:Number,
      default:0
  },	
  lack_of_concentration:{
      type:Number,
      default:0
  },	
  visual_disturbances:{
      type:Number,
      default:0
  },	
  receiving_blood_transfusion:{
      type:Number,
      default:0
  },	
  receiving_unsterile_injections:{
      type:Number,
      default:0
  },	
  coma:{
      type:Number,
      default:0
  },	
  stomach_bleeding:{
      type:Number,
      default:0
  },	
  distention_of_abdomen:{
      type:Number,
      default:0
  },	
  history_of_alcohol_consumption:{
      type:Number,
      default:0
  },	
  fluid_overload:{
      type:Number,
      default:0
  },	
  blood_in_sputum:{
      type:Number,
      default:0
  },	
  prominent_veins_on_calf:{
      type:Number,
      default:0
  },	
  palpitations:{
      type:Number,
      default:0
  },	
  painful_walking:{
      type:Number,
      default:0
  },	
  pus_filled_pimples:{
      type:Number,
      default:0
  },	
  blackheads:{
      type:Number,
      default:0
  },	
  scurring:{
      type:Number,
      default:0
  },	
  skin_peeling:{
      type:Number,
      default:0
  },	
  silver_like_dusting:{
      type:Number,
      default:0
  },	
  small_dents_in_nails:{
      type:Number,
      default:0
  },	
  inflammatory_nails:{
      type:Number,
      default:0
  },	
  blister:{
      type:Number,
      default:0
  },	
  red_sore_around_nose:{
      type:Number,
      default:0
  },	
  yellow_crust_ooze:{
      type:Number,
      default:0
  },	
  prognosis:{
      type:Number,
      default:0
  },

  })
);

module.exports = Data;